//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcBuilderWebApp
{
    public partial class Configurations
    {
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        protected global::System.Web.UI.WebControls.Panel pnlEmptyMessage;
        protected global::System.Web.UI.WebControls.Repeater rptConfigurations;
    }
}

