//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcBuilderWebApp
{
    public partial class MasterPage
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.ScriptManager ScriptManagerMaster;
        protected global::System.Web.UI.WebControls.HyperLink lnkHome;
        protected global::System.Web.UI.WebControls.HyperLink lnkBuild;
        protected global::System.Web.UI.WebControls.HyperLink lnkConfigurations;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
    }
}

