//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcBuilderWebApp.CustomControls
{
    public partial class ComponentDisplay
    {
        protected global::System.Web.UI.WebControls.Label lblComponentName;
        protected global::System.Web.UI.WebControls.Label lblManufacturer;
        protected global::System.Web.UI.WebControls.Label lblPrice;
        protected global::System.Web.UI.WebControls.Button btnSelect;
    }
}

